[mgr]
show_hidden = true
sort_by = "size"
sort_dir_first = true
sort_reverse = true
scrolloff = 3

prepend_keymap = [
  { on = "!", run = "shell '~/yazi_shell.sh \"$1\"'", desc = "Open shell here" },
  { on = "gs", run = "shell '~/yazi_shell.sh \"$1\"'", desc = "Open shell here" }
]

[preview]
max_width = 1000
max_height = 1000
ueberzug = true
prepend_meta = true

[status]
left = ["mode", "size", "created", "modified"]
right = ["permissions", "owner", "group"]

[command.create_symlink]
run = "ln -s \"$1\" \"$(pwd)/$1-symlink\""
desc = "Create symlink in current directory"

[command.toggle_meta]
run = '''
if [[ "$YAZI_META" == "true" ]]; then
    export YAZI_META="false"
else
    export YAZI_META="true"
fi
'''
desc = "Toggle metadata preview"

[command.print_test]
run = 'echo "✅ Hello from Yazi!"'
desc = "Test print command"

[command.dir_graph]
run = "~/.config/yazi/yazi-size-graph.sh \"$1\""
desc = "Show directory size graph"

[opener]
edit = [
  { run = 'env NVIM_APPNAME=LazyVIM nvim "$@"', block = true, for = "unix" }
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { name = "*.py", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.yaml", use = "edit" },
  { name = "*.yml", use = "edit" },
  { name = "*.md", use = "edit" }
]

[keymap]
"ss" = "create_symlink"

[log]
level = "info"
